name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-qt
    
    - name: Run tests
      run: |
        python run_tests.py
      env:
        PYTHONPATH: ${{ github.workspace }}
  
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-qt
    
    - name: Run tests
      run: |
        python run_tests.py
    
    - name: Build executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile --windowed --icon=app_icon.ico main.py
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/main.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 